name: Weather-app CI

on:
  pull_request:
  push:
    branches:
      - master
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
        run: npm install
